[[stake]]
address = 'ppMLM6t6GLmZb7xzx617TTHQPdHHRNSfB8PjtGe8YNbWAo4BRYfnNYZxCj62pLY8gXZqsrx7TaBS17dRsHoE81wLHgMHaYoq2z6GHX7KAD5TiRcX1w5ctiSqV3idx3SJdAe'
amount = 21_418_000_000_000

[[stake]]
address = '21mif6HvgdLoJtLzibs42LZDtnwkf3518yfhBsTfVim2WZa3j8H9E64JHK4KWdc7W5KMDvoMk7zdY9ddeE1VuNQsks1suJzWDNf5mL5yBqjzdkdfWPaJjyg4rvJ1GqREuDBq'
amount = 50_000_000_000_000

[[stake]]
address = 'nXXJNC4e7u92anSCNyPoj3mp9ddmDNHJz7bTdYMeuMTTNhpQyByt9ezrDjWvxvoX3RxrrGkLTET2iBHnbqvx4d4huyynAy2UNvhzXm4PvKR4GQjdCRwXetmJhLWAz2mpAfV'
amount = 3_000_000_000_000

[[stake]]
address = 'yWynRKzN1BdKJQDtv848LdSRJrFqdrudoDTnre2fiWAC8XvZuTb4UAjAkStu9idW4N9R8ncnuk4dsMFPE63AgF3Jbdemax5pH2YMkngxkjEBBaRpEV1wHHZh2ecS3vKeGiN'
amount = 3_061_000_000_000

[[stake]]
address = 'yc8aiwLXGpXjHFgP6kgEHpTq6vewtqGHCNKdkvRndqeGsMrkxeEEX26FMY3sHFrMMxDyUSRFWbeWBaWkuMkErotcC4qhvDReKGddJ5g32G6parJsu43PBCnsvtumypnayqy'
amount = 2_540_000_000_000

[[stake]]
address = 'qW2XxCLkoYZMHHonixqxLA5kitZNb7PhH2QsiVZfE1TPA6W2w7AMwgA6LPg4JE5k64j3xfgCX8WweGC5n8bjWbpbBEiiWdBEsATu1AyvRv2oVSy6qYtwYEkkNCC91qj8DW8'
amount = 1_990_000_000_000

[[stake]]
address = '263iutoFfU2Hc3nRN3K3Jic5hBTL6dgPTzsavWfGRmgVzKp9g2uAmPmBnHPgej2i55Xrg5McFFW2Tp4EAJ51ukLTmUwRri4SE4ESKEkqPiEqV9xt1YUpKdFJ5TbU7a1rbroi'
amount = 2_950_000_000_000

[[moonlight_account]]
address = '23Cf8B373NTWyCS6WXvJAt3hps3tvf4UH5CB4zNx5sbdhevsNvYzJ4FBWmc7MqFEPNgLzGNw7Ad6L8MoMyPer3cxUzead5Ku6sYr7xqXBMMqzEWQ3dVANGmp3Zkni721w37d'
balance = 11_578_000_000_000

[[moonlight_account]]
address = 'ppMLM6t6GLmZb7xzx617TTHQPdHHRNSfB8PjtGe8YNbWAo4BRYfnNYZxCj62pLY8gXZqsrx7TaBS17dRsHoE81wLHgMHaYoq2z6GHX7KAD5TiRcX1w5ctiSqV3idx3SJdAe'
balance = 1_500_000_000_000

[[moonlight_account]]
address = 'sN4GfdHXZuD6kzXvd2eXaNXeL4GoGqRn5Q6bZZFGQFYQwiq5xaeLP7pJHCA5aHsLXpMr4CHtD5fQyVRngmk9v4SC5y7ugLBQ2yuJt1GkxGPQtWnJqafNQHhbH9xYwDn7wEk'
balance = 1_018_000_000_000

[[moonlight_account]]
address = '21mif6HvgdLoJtLzibs42LZDtnwkf3518yfhBsTfVim2WZa3j8H9E64JHK4KWdc7W5KMDvoMk7zdY9ddeE1VuNQsks1suJzWDNf5mL5yBqjzdkdfWPaJjyg4rvJ1GqREuDBq'
balance = 86_250_000_000_000

[[moonlight_account]]
address = 'nXXJNC4e7u92anSCNyPoj3mp9ddmDNHJz7bTdYMeuMTTNhpQyByt9ezrDjWvxvoX3RxrrGkLTET2iBHnbqvx4d4huyynAy2UNvhzXm4PvKR4GQjdCRwXetmJhLWAz2mpAfV'
balance = 115_000_000_116

[[moonlight_account]]
address = 'yWynRKzN1BdKJQDtv848LdSRJrFqdrudoDTnre2fiWAC8XvZuTb4UAjAkStu9idW4N9R8ncnuk4dsMFPE63AgF3Jbdemax5pH2YMkngxkjEBBaRpEV1wHHZh2ecS3vKeGiN'
balance = 54_000_000_000

[[moonlight_account]]
address = 'yc8aiwLXGpXjHFgP6kgEHpTq6vewtqGHCNKdkvRndqeGsMrkxeEEX26FMY3sHFrMMxDyUSRFWbeWBaWkuMkErotcC4qhvDReKGddJ5g32G6parJsu43PBCnsvtumypnayqy'
balance = 5_000_000_000

[[moonlight_account]]
address = 'qW2XxCLkoYZMHHonixqxLA5kitZNb7PhH2QsiVZfE1TPA6W2w7AMwgA6LPg4JE5k64j3xfgCX8WweGC5n8bjWbpbBEiiWdBEsATu1AyvRv2oVSy6qYtwYEkkNCC91qj8DW8'
balance = 21_000_000_000

[[moonlight_account]]
address = '263iutoFfU2Hc3nRN3K3Jic5hBTL6dgPTzsavWfGRmgVzKp9g2uAmPmBnHPgej2i55Xrg5McFFW2Tp4EAJ51ukLTmUwRri4SE4ESKEkqPiEqV9xt1YUpKdFJ5TbU7a1rbroi'
balance = 45_000_000_000

[[moonlight_account]]
address = 'xn8a8WN4GkU2uqBCv7VfHFgCDKaQY9kmeXSQhBkLtRVRpRY1JM7J59MaWRtG8RRQRJU1Foc24hQHHpqR63cQvqzqvbZd3nz6bR3JBjpRrezBaB7kPZ1ecLZYQcChS9q2xYd'
balance = 1_030_000_000_000

[[moonlight_account]]
address = 'tufXcEBhQaNafTWfa1sfgr1WCz3HQ2YiwEsQym53e1J9XZTwroPHbwJAhpZr8SBJ3ba91BfBKpdrJmYKVEkGYYwS2NRVzzxD6VHawVxdxdtM3CWDdALs923rthFYMqdUKfq'
balance = 1_060_762_500_000

[[moonlight_account]]
address = '26PDjnCHrZvfss8c31R9XBczaKDR1sudYxynL9ggtYdiQqQxLDXrpGWBY8ez3giTMV46QgPKTind4PzrCzKgT3ZA9nCNEyh5UFDk9myebJj2VS9PEGed3V4yQcp3yfg28Hi9'
balance = 1_095_000_000_000

[[moonlight_account]]
address = 'pM2PKWckAPFM22QTDRdTz8PQXMhLpxrEFog9LHBVsX3wJLog7eebNc9ASyvnF8Y3UV3GrT3GqWNMU6BsJejvroaxm7drNGmx1ZqZ4ViJnUqUDr4DZXwc92u2oxjG1DYuvRD'
balance = 25_260_000_000

[[moonlight_account]]
address = 'rHipWB74MgfXiVRmvM6FVmyp4Gnhc8CugwAhvNSDS5AN68EbbNrpo1yW6eyQso8F4dtZDnmMReMkpqcRrMFYX1WPx9pRkk3PJ6fQuamZMz3NbvGkSqPxkZtTPWsKvbJFu78'
balance = 1_000_000_000_000

[[moonlight_account]]
address = 'sYNLrVLbVU6wExWWJTZ5eh4r8hTFkLGScLmmCbewS4eZNMUGVs2GCV52PsKsXg7vommuaDRAjYez9USov1isdqAG9EY93iTihSftkxFBvibbewQWub6MepZsCBgK2FBkMpU'
balance = 1_004_890_000_000

[[moonlight_account]]
address = 'y5PgL2qrMpbquTkwkbt77JYZNbtsccPoTRoRrhkCmQ4sCQuH5iojVy6zM64ZC3oZnk3F4PuYnjAGR3Vj8hdVodBDDfurgq29iqU8wbzNcnfTuuC91AtXjkvXqe7HUwsjxqs'
balance = 272_000_000_000

[[moonlight_account]]
address = 'pvUFfijuwv7z41YzuxSs6wBzvdSYaGcsqK8nP3CJuTypXeUq4kwcXgXKftP2jgJfFFq4tb8ka5UATHwuDdwkicvbULW2xSeeHVFf8tS2qQNSFM8TVtEZrVyjKBgEFvzUCq9'
balance = 850_000_000_000

[[moonlight_account]]
address = 'uN9LfzzkYFg7ntYpjUZU5ZZwn5GsZbVmnG2xovbB5vWjuBwmeTyJVtRESwuRS3t1qpudmTbS644D1ywhkEgENdNYcv75WqxiGDX2SkbLHFakD5AjDccTpH6RFDRfQEaYLCQ'
balance = 899_000_000_000

[[moonlight_account]]
address = 'u96pqz8xYjc34MtLwQUL7qL8Qc9rkPmJ7ikDTNXTRXHNhrDSQfc215wBdjJXsV6N2E8oDypE3Q35LfrheTLjeN7BKH2vY2UaszvczpnebMvj7yu2LXgXmXAp6wvH9LEudFM'
balance = 237_000_000_000

[[moonlight_account]]
address = '23WsWMfXQ6hkyKyHCg1xsnCWet7gxWher5jyNJAwH61kpSFryFz3fPKUri1oMK29qq4vC3CZfKnneF5jwaB3SD8ZGxUPeKUKZyojgkuTtH8NKW9FR4NFc8NCjq9ZBLsciiES'
balance = 47_000_000_000

[[moonlight_account]]
address = 'xURkX7qRPj977Qh9dr4x79BnfngRMAXW53aUSXjVaPwAdwhq3JSCKntMxtPy6Qiub8jdRtQy3suq4VUqoxZTdw5Qocdc5EfYqwMQ6NoXydUdeu2CUj3VhMQSo59MDCCs4nu'
balance = 1_984_569_100_000

[[moonlight_account]]
address = 'nMXpdxMRGAfGixMDpaXucx6Qq5JSsHHHPFMtB16RyBhk5BPRRM1nti7o78bSLGFtc9u9ZqGtn6NiKMntA7xQi2Mk7Xn49iKzd2NkDdVqHv8FwkVvbj4hmJvsGP6gvijt6Nh'
balance = 225_905_237_829
